name: Limit PRs

on:
  pull_request:
    branches:
      - staging

jobs:
  limit_staging_pr:
    runs-on: ubuntu-latest
    name: Limits PR to staging
    steps:
      - name: Limit action step
        id: limit_action
        uses: LukBukkit/action-pr-limits@v1
        with:
          whitelist: |
            dev